/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spinning.top;

import java.util.Random;

/**
 *
 * @author Jaime Pantoja
 */
public class spinning extends javax.swing.JFrame {

    int contador=0;
    int contador2=1;
    int num_jug=1;
    int suma=0;
    int suma2=0;
    int bolsa=5;
    int decremento=0;
    int decremento2=0;
    int decremento3=2;
    int decremento4=2;
    
    int nivel=0;
    int cara=0;
    int j1,j2,j3,j4=-1;
    int acumulado=0;
    /**
     * Creates new form spinning
     */
    public spinning() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl4 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl44 = new javax.swing.JLabel();
        lbl33 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        text4 = new javax.swing.JTextField();
        text3 = new javax.swing.JTextField();
        text1 = new javax.swing.JTextField();
        lbldado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        button1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spinning top");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Play zone"));

        lbl4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("Player4");

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Player1\n");

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Player3");

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Player2");

        lbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl11.setText("Coins");

        lbl22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl22.setText("Coins");

        lbl44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl44.setText("Coins");

        lbl33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl33.setText("Coins");

        text2.setForeground(new java.awt.Color(204, 0, 0));
        text2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text2.setText("0");
        text2.setCaretColor(new java.awt.Color(51, 51, 51));
        text2.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        text2.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        text4.setForeground(new java.awt.Color(204, 0, 0));
        text4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text4.setText("0");
        text4.setCaretColor(new java.awt.Color(51, 51, 51));
        text4.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        text4.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        text3.setForeground(new java.awt.Color(204, 0, 0));
        text3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text3.setText("0");
        text3.setCaretColor(new java.awt.Color(51, 51, 51));
        text3.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        text3.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        text1.setForeground(new java.awt.Color(204, 0, 0));
        text1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text1.setText("0");
        text1.setCaretColor(new java.awt.Color(51, 51, 51));
        text1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        text1.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        lbldado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldado.setText("?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl33, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(text3))
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl11, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(text1)
                            .addComponent(lbldado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(144, 144, 144))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl44, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(text4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl22, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(text2))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl44)
                            .addComponent(lbl22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbldado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Config zone"));

        jLabel1.setText("Coins per player:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "20", "30" }));

        button1.setBackground(new java.awt.Color(0, 153, 0));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Play");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(button1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button1)
                .addGap(24, 24, 24))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Acumulated"));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jTextField1.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Winner"));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("?");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Spin around -> Player #");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reiniciar juego");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       
        int nivel=0;  
        
        nivel= jComboBox1.getSelectedIndex();
        if(nivel==0){
            text1.setText(Integer.toString(5));
            text2.setText(Integer.toString(5));
            text3.setText(Integer.toString(5));
            text4.setText(Integer.toString(5));
            j1=j2=j3=j4=5;
            
        }
        if(nivel==1){
            text1.setText(Integer.toString(10));
            text2.setText(Integer.toString(10));
            text3.setText(Integer.toString(10));
            text4.setText(Integer.toString(10));
            j1=j2=j3=j4=10;
        }
        
         if(nivel==2){
            text1.setText(Integer.toString(20));
            text2.setText(Integer.toString(20));
            text3.setText(Integer.toString(20));
            text4.setText(Integer.toString(20));
            j1=j2=j3=j4=20;
        }
         
         if(nivel==3){
            text1.setText(Integer.toString(30));
            text2.setText(Integer.toString(30));
            text3.setText(Integer.toString(30));
            text4.setText(Integer.toString(30));
            j1=j2=j3=j4=30;
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Random n = new Random();
        cara = (int)(n.nextDouble()*6+1);
            switch(cara){
                case 1:
                    lbldado.setText("Pon 1");
                    switch (num_jug) {
                        case 1:
                            if(j1>0){j1--;}
                            acumulado++;
                            num_jug++;
                            break;
                        case 2:
                            if(j2>0){j2--;}
                            acumulado++;
                            num_jug++;
                            break;
                        case 3:
                            if(j3>0){j3--;}
                            acumulado++;
                            num_jug++;
                            break;
                        case 4:
                            if(j4>0){j4--;}
                            acumulado++;
                            num_jug=1;
                            break;
                      
                    }
                    jButton1.setText("Play - player # "+Integer.toString(num_jug));
                            
                    text1.setText(Integer.toString(j1));
                    text2.setText(Integer.toString(j2));
                    text3.setText(Integer.toString(j3));
                    text4.setText(Integer.toString(j4));
                    jTextField1.setText(Integer.toString(acumulado));
                    break;

                case 2:
                    lbldado.setText("Pon 2");
                    switch (num_jug) {
                        case 1:
                            if(j1>0){j1-=2;}
                            acumulado+=2;
                            num_jug++;
                            break;
                        case 2:
                            if(j2>0){j2-=2;}
                            acumulado+=2;
                            num_jug++;
                            break;
                        case 3:
                            if(j3>0){j3-=2;}
                            acumulado+=2;
                            num_jug++;
                            break;
                        case 4:
                            if(j4>0){j4-=2;}
                            acumulado+=2;
                            num_jug=1;
                            break;
                      
                    }
                    jButton1.setText("Play - player # "+Integer.toString(num_jug));
                            
                    text1.setText(Integer.toString(j1));
                    text2.setText(Integer.toString(j2));
                    text3.setText(Integer.toString(j3));
                    text4.setText(Integer.toString(j4));
                    jTextField1.setText(Integer.toString(acumulado));
                    break;
                case 3:
                    lbldado.setText("Toma 1");
                    switch (num_jug) {
                        case 1:
                            if(acumulado>0){acumulado--;}
                            if(j1>0){j1++;}
                            num_jug++;
                            break;
                        case 2:
                            if(acumulado>0){acumulado--;}
                            if(j2>0){j2++;}
                            num_jug++;
                            break;
                        case 3:
                            if(acumulado>0){acumulado--;}
                            if(j3>0){j3++;}
                            num_jug++;
                            break;
                        case 4:
                            if(acumulado>0){acumulado--;}
                            if(j4>0){j4++;}
                            num_jug=1;
                            break;
                      
                    }
                    jButton1.setText("Play - player # "+Integer.toString(num_jug));
                            
                    text1.setText(Integer.toString(j1));
                    text2.setText(Integer.toString(j2));
                    text3.setText(Integer.toString(j3));
                    text4.setText(Integer.toString(j4));
                    jTextField1.setText(Integer.toString(acumulado));
                    break;
                case 4:
                    lbldado.setText("Toma 2");
                    switch (num_jug) {
                        case 1:
                            if(acumulado>0){acumulado-=2;}
                            if(j1>0){j1+=2;}
                            num_jug++;
                            break;
                        case 2:
                            if(acumulado>0){acumulado-=2;}
                            if(j2>0){j2+=2;}
                            num_jug++;
                            break;
                        case 3:
                            if(acumulado>0){acumulado-=2;}
                            if(j3>0){j3+=2;}
                            num_jug++;
                            break;
                        case 4:
                            if(acumulado>0){acumulado-=2;}
                            if(j4>0){j4+=2;}
                            num_jug=1;
                            break;
                      
                    }
                    jButton1.setText("Play - player # "+Integer.toString(num_jug));
                            
                    text1.setText(Integer.toString(j1));
                    text2.setText(Integer.toString(j2));
                    text3.setText(Integer.toString(j3));
                    text4.setText(Integer.toString(j4));
                    jTextField1.setText(Integer.toString(acumulado));
                    break;
                case 5:
                    lbldado.setText("Toma todo");
                    switch (num_jug) {
                        case 1:
                            if(j1>0){
                                j1+=acumulado;
                                acumulado=0;
                                num_jug++;
                            }
                            break;
                        case 2:
                            if(j2>0){
                                j2+=acumulado;
                                acumulado=0;
                                num_jug++;
                            }
                            break;
                        case 3:
                            if(j3>0){
                                j3+=acumulado;
                                acumulado=0;
                                num_jug++;
                            }
                            break;
                        case 4:
                            if(j4>0){
                                j4+=acumulado;
                                acumulado=0;
                                num_jug=1;
                            }
                            break;
                      
                    }
                    jButton1.setText("Play - player # "+Integer.toString(num_jug));
                            
                    text1.setText(Integer.toString(j1));
                    text2.setText(Integer.toString(j2));
                    text3.setText(Integer.toString(j3));
                    text4.setText(Integer.toString(j4));
                    jTextField1.setText(Integer.toString(acumulado));
                    break;
                case 6:
                    lbldado.setText("Todos ponen");
                    switch (num_jug) {
                        case 1:
                            if(j1>0){j1--;acumulado++;}
                            if(j2>0){j2--;acumulado++;}
                            if(j3>0){j3--;acumulado++;}
                            if(j4>0){j4--;acumulado++;}
                            num_jug++;
                            break;
                        case 2:
                            if(j1>0){j1--;acumulado++;}
                            if(j2>0){j2--;acumulado++;}
                            if(j3>0){j3--;acumulado++;}
                            if(j4>0){j4--;acumulado++;}
                            num_jug++;
                            break;
                        case 3:
                            if(j1>0){j1--;acumulado++;}
                            if(j2>0){j2--;acumulado++;}
                            if(j3>0){j3--;acumulado++;}
                            if(j4>0){j4--;acumulado++;}
                            num_jug++;
                            break;
                        case 4:
                            if(j1>0){j1--;acumulado++;}
                            if(j2>0){j2--;acumulado++;}
                            if(j3>0){j3--;acumulado++;}
                            if(j4>0){j4--;acumulado++;}
                            num_jug=1;
                            break;
                      
                    }
                    jButton1.setText("Play - player # "+Integer.toString(num_jug));
                            
                    text1.setText(Integer.toString(j1));
                    text2.setText(Integer.toString(j2));
                    text3.setText(Integer.toString(j3));
                    text4.setText(Integer.toString(j4));
                    jTextField1.setText(Integer.toString(acumulado));
                    break;        
            }
            if(j2<=0&&j3<=0&&j4<=0){
                jTextField2.setText(Integer.toString(1));
                jButton1.setEnabled(false);
            }
            if(j1<=0&&j3<=0&&j4<=0){
                jTextField2.setText(Integer.toString(2));
                jButton1.setEnabled(false);
            }
            if(j1<=0&&j2<=0&&j4<=0){
                jTextField2.setText(Integer.toString(3));
                jButton1.setEnabled(false);
            }
            if(j1<=0&&j2<=0&&j3<=0){
                jTextField2.setText(Integer.toString(4));
                jButton1.setEnabled(false);
            }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        jButton1.setText("Play - player # "+Integer.toString(num_jug)); 
        button1.setEnabled(false);
        jComboBox1.setEnabled(false);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_button1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
      
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        j1=j2=j3=j4=-1;
        acumulado=0;
        num_jug=1;
        nivel=0;
        cara=0;
        text1.setText(Integer.toString(j1));
        text2.setText(Integer.toString(j2));
        text3.setText(Integer.toString(j3));
        text4.setText(Integer.toString(j4));
        jTextField1.setText(Integer.toString(acumulado));
        jButton1.setEnabled(false);
        button1.setEnabled(true);
        jComboBox1.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spinning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spinning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spinning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spinning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spinning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl33;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl44;
    private javax.swing.JLabel lbldado;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    // End of variables declaration//GEN-END:variables
}
